- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup file
      include_vars: vars/bastion_setup

    - name: Import Output Variables
      include_vars: vars/output_vars

    - name: Create key pair
      ec2_key:
        name: vprofile-key
        region: "{{ region }}"
      register: key_out
    #- debug:
    #   var: key_out
      
    - name: Save private key
      copy: 
        content: "{{key_out.key.private_key}}"
        dest: "./vprofile-key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security Group
      ec2_group:
        name: bastion-host-sg
        description: Creating Security Group for bastionHost
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: bastionHost_out

    - name: Create EC2 instance
      ec2:
        key_name: vprofile-key
        region: "{{region}}"
        instance_type: t2.micro
        image: "{{bastion_ami}}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "BastionHost"
          Project: "Vprofile"
          Group: "DevOps Team"
        exact_count: 1
        count_tag:
          Name: "BastionHost"
          Project: "Vprofile"
          Group: "DevOps Team"
        groupId: "{{bastionHost_out.group_id}}"
      register: bastionHost_out
            