- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup file
      include_vars: vars/vpc_setup

    - name: Import Output Variables
      include_vars: vars/vpc_output_vars

    - name: Create key pair
      ec2_key:
        name: bastion_key
        region: "{{ region }}"
      register: key_out
    #- debug:
    #   var: key_out
      
    - name: Save private key
      copy: 
        content: "{{key_out.key.private_key}}"
        dest: "./bastion_key.pem"
        mode: 0600
      when: key_out.changed

    - name: Create Security Group
      ec2_group:
        name: bastion-host-sg
        description: Creating Security Group for bastionHost
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: "{{MYIP}}"
      register: sg_out
    #- debug:
    #  var: sg_out

    - name: Create EC2 instance
      amazon.aws.ec2_instance:
        name: Bastion Host
        instance_type: t2.micro
        image_id: "{{ bastion_ami }}"
        region: "{{region}}"
        key_name: "bastion_key"
        vpc_subnet_id: "{{ PubSub1a }}"
        security_group: "{{ sg_out.group_id }}"
        wait_timeout: 300
        network:
          assign_public_ip: true
        tags:
          Name: "Bastion Host"
          Environment: Testing
        wait: true
      register: bastionHost_out