- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variable
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout

    - name: Creating Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: present
        tags:
          Name: "Vprofile_IGT"
      register: igw
    - name: Debug IGW Output 
      debug:
        var: igw

    - name: Create Public Subnet 1a
      ec2_vpc_subnet:
        state: "{{state}}"
        vpc_id: "{{ vpcout.vpc.id }}"
        cidr: "{{PubSub1Cidr}}"
        az: "{{zone1}}" 
        map_public_ip_on_launch: true
        tags:
          Name: Public Subnet 1a
      register: pubsub1_out
