- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variable
      include_vars: vars/vpc_setup

    - name: Create Vprofile VPC
      ec2_vpc_net:
        name: "{{vpc_name}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostname: yes
        tenancy: default
        state: "{{state}}"
      region: vpcout

    - name: Create Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{vpc_name}}"
        state: "{{state}}"
      register: igw