- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC variable
      include_vars: vars/vpc_setup

    - name: Vprofile VPC
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpcCidr }}"
        region: "{{ region }}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{ state }}"
      register: vpcout

    - name: Public Subnet 1a
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub1Cidr }}"
        az: "{{ zone1 }}" 
        map_public: true
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_pubsub1
      register: pubsub1_out
    #- debug:
    #    var: pubsub1_out

    - name: Public Subnet 1b
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub2Cidr }}"
        az: "{{ zone2 }}" 
        map_public: true
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_pubsub2
      register: pubsub2_out

    - name: Public Subnet 1c
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PubSub3Cidr }}"
        az: "{{ zone3 }}" 
        map_public: true
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_pubsub3
      register: pubsub3_out
      
    - name: Private Subnet 1a
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub1Cidr }}"
        az: "{{ zone1 }}" 
        map_public: false
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_privsub1
      register: privsub1_out

    - name: Private Subnet 1b
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub2Cidr }}"
        az: "{{ zone2 }}" 
        map_public: false
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_privsub2
      register: privsub2_out

    - name: Private Subnet 1c
      ec2_vpc_subnet:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ PrivSub3Cidr }}"
        az: "{{ zone3 }}" 
        map_public: false
        state: "{{ state }}"
        resource_tags:
          Name: Vprofile_privsub3
      register: privsub3_out

    - name: Internet Gateway
      ec2_vpc_igw:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        state: "{{ state }}"
        tags:
          Name: "Vprofile_IGT"
      register: igw
    #- name: Debug IGW Output 
    #  debug:
    #    var: igw

    - name: Public route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: Vprofile_public_RT
        subnets:
          - "{{ pubsub1_out.subnet.id }}"
          - "{{ pubsub2_out.subnet.id }}"
          - "{{ pubsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
      register: vprofile_public_RT
      
    - name: Nat gateway
      ec2_vpc_nat_gateway:
        state: "{{ state }}"
        subnet_id: "{{ pubsub1_out.subnet.id }}"
        wait: yes
        region: "{{ region }}"
        if_exist_do_not_create: true
        tags:
          Name: Vprofile_NAT
      register: nat_gateway
    #- debug:
    #   var: nat_gateway
    
    - name: Private route table
      ec2_vpc_route_table:
        vpc_id: "{{ vpcout.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: Vprofile_private_RT
        subnets:
          - "{{ privsub1_out.subnet.id }}"
          - "{{ privsub2_out.subnet.id }}"
          - "{{ privsub3_out.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ nat_gateway.nat_gateway_id }}"
      register: vprofile_private_RT

    - debug:
        var: "{{ item }}"
      loop:
        - vpcout.vpc.id
        - pubsub1_out.subnet.id
        - pubsub2_out.subnet.id
        - pubsub3_out.subnet.id
        - privsub1_out.subnet.id
        - privsub2_out.subnet.id
        - privsub3_out.subnet.id
        - igw.gateway_id
        - nat_gateway.nat_gateway_id
        - vprofile_public_RT.route_table.id
        - vprofile_private_RT.route_table.id

    - set_facts:
        vpc_id: "{{ vpcout.vpc.id }}"
        //PubSub1a: "{{ pubsub1_out.subnet.id }}"
        //PubSub1b: "{{ pubsub2_out.subnet.id }}"
        //PubSub1c: "{{ pubsub3_out.subnet.id }}"
        //PrivSub1a: "{{ privsub1_out.subnet.id }}"
        //PrivSub1b: "{{ privsub2_out.subnet.id }}"
        //PrivSub1c: "{{ privsub3_out.subnet.id }}"
        //IGT: "{{ igw.gateway_id }}"
        //NAT: "{{ nat_gateway.nat_gateway_id }}"
        //Pub_RT: "{{ vprofile_public_RT.route_table.id }}"
        //Priv_RT: "{{ vprofile_private_RT.route_table.id }}"
      cacheable: yes