---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup  variables
      include_vars: vars/vpc_setup

    - name: Import Output Variables
      include_vars: vars/vpc_output_vars
  
    - name: Import Vprofile setup variables
      include_vars: vars/vprostacksetup

    - name: Create key pair
      ec2_key:
        name: vpro-key
        region: "{{ region }}"
      register: vprokey_out
    #- debug:
    #   var: vprokey_out
      
    - name: Save private key
      copy: 
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./vpro-key.pem"
        mode: 0600
      when: vprokey_out.changed
    
    - name: Security Group for Load Balancer
      amazon.aws.ec2_group:
        name: vproELB-sg
        description: Security Group for Load Balancer
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: sgELBSG_out

    - name: Security Group for EC2 stack
      amazon.aws.ec2_group:
        name: vproStack-sg
        description: Security Group for EC2 stack
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ sgELBSG_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: vproStackSG_out

    - name: Allow all traffic from everywhere within SG
      ec2_group:
        name: vproStack-sg
        description: Allow all traffic from everywhere within SG
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vproStackSG_out.group_id }}"

    - name: Nginx EC2 Instance
      ec2:
        image: "{{ nginx_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        vpc_subnet_id: "{{ PrivSub1Cidr }}"
        key: "{{ vpro-key }}"
        group_id: "{{ vproStackSG_out.group_id }}"
        wait: yes
        wait_timeout: 300
        instance_tags:
          Name: "Web01"
          Project: "Vprofile"
          Owner: "Devops Team"
        exact_count: 1
        count_tag:
          Name: "Web01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: web01_out
