---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup  variables
      include_vars: vars/vpc_setup

    - name: Import Output Variables
      include_vars: vars/vpc_output_vars
  
    - name: Import Vprofile setup variables
      include_vars: vars/vprostacksetup

    - name: Create key pair
      ec2_key:
        name: vpro-key
        region: "{{ region }}"
      register: vprokey_out
    #- debug:
    #   var: vprokey_out
      
    - name: Save private key
      copy: 
        content: "{{vprokey_out.key.private_key}}"
        dest: "./vpro-key.pem"
        mode: 0600
      when: vprokey_out.changed
    
    - name: Security Group for Load Balancer
      ec2_group:
        name: vpro-ELB-sg
        description: Security Group for Load Balancer
        region: "{{region}}"
        vpc_id: "{{vpc_id}}"
        rule:
          - proto: tcp
          - from_port: 80
          - to_port: 80
          - cidr: 0.0.0.0/0
      register: sgLB_out