---
- name: Setup Vprofile Stack
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Import VPC setup  variables
      include_vars: vars/vpc_setup

    - name: Import Output Variables
      include_vars: vars/vpc_output_vars
  
    - name: Import Vprofile setup variables
      include_vars: vars/vprostacksetup

    - name: Create key pair
      ec2_key:
        name: loginkey_vpro
        region: "{{ region }}"
      register: vprokey_out
    #- debug:
    #   var: vprokey_out
      
    - name: Save private key
      copy: 
        content: "{{ vprokey_out.key.private_key }}"
        dest: "./loginkey_vpro.pem"
        mode: 0600
      when: vprokey_out.changed
    
    - name: Security Group for Load Balancer
      amazon.aws.ec2_group:
        name: vproELB_sg
        description: Security Group for Load Balancer
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: 0.0.0.0/0
      register: vproELBsg_out

    - name: Security Group for EC2 stack
      amazon.aws.ec2_group:
        name: vproStack_sg
        description: Security Group for EC2 stack
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: tcp
            from_port: 80
            to_port: 80
            group_id: "{{ vproELBsg_out.group_id }}"

          - proto: tcp
            from_port: 22
            to_port: 22
            group_id: "{{ BastionSGid }}"
      register: vproStackSG_out

    - name: Allow all traffic from everywhere within SG
      ec2_group:
        name: vproStack_sg
        description: Allow all traffic from everywhere within SG
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        purge_rules: no
        rules:
          - proto: all
            group_id: "{{ vproStackSG_out.group_id }}"

    - name: Nginx EC2 Instance
      amazon.aws.ec2_instance:
        name: "Web01"
        image_id: "{{ nginx_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_subnet_id: "{{ PrivSub1a }}"
        key_name: "loginkey_vpro"
        security_group: "{{ vproStackSG_out.group_id }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "Web01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: web01_out

    - name: Tomcat EC2 Instance
      amazon.aws.ec2_instance:
        name: "App01"
        image_id: "{{ tomcat_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_subnet_id: "{{ PrivSub1b }}"
        key_name: "loginkey_vpro"
        security_group: "{{ vproStackSG_out.group_id }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "App01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: app01_out

    - name: Memcache EC2 Instance
      amazon.aws.ec2_instance:
        name: "Mc01"
        image_id: "{{ memcache_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_subnet_id: "{{ PrivSub1c }}"
        key_name: "loginkey_vpro"
        security_group: "{{ vproStackSG_out.group_id }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "Mc01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: mc01_out

    - name: RabbitMQ EC2 Instance
      amazon.aws.ec2_instance:
        name: "rmq01"
        image_id: "{{ rmq_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_subnet_id: "{{ PrivSub1a }}"
        key_name: "loginkey_vpro"
        security_group: "{{ vproStackSG_out.group_id }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "rmq01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: rmq01_out

    - name: MySQL EC2 Instance
      amazon.aws.ec2_instance:
        name: "db01"
        image_id: "{{ mysql_ami }}"
        instance_type: "t2.micro"
        region: "{{ region }}"
        vpc_subnet_id: "{{ PrivSub1b }}"
        key_name: "loginkey_vpro"
        security_group: "{{ vproStackSG_out.group_id }}"
        wait: true
        wait_timeout: 300
        tags:
          Name: "db01"
          Project: "Vprofile"
          Owner: "Devops Team"
      register: db01_out
    #- debug:
    #   var: db01_out.instances[0].network_interfaces[0].private_ip_address

    
    - name: Creating Load Balancer
      local_action:
        module: ec2_elb_lb
        name: "Vprofile-elb"
        region: "{{ region }}"
        state: "{{ state }}"
        instance_ids: "{{ web01_out.instance_ids }}"
        purge_instance_ids: true
        security_group_ids: "{{ vproELBsg_out.group_id }}"
        subnets: 
          - "{{ PrivSub1a }}"
          - "{{ PrivSub1b }}"
          - "{{ PrivSub1c }}"
        listeners:
          - protocol: tcp
            load_balancer_port: 80
            instance_port: 80

    - name: Insert/Update Host IP & Names in the file provision-stack/group_vars/hostsip 
      blockinfile:
        path: provision-stack/group_vars/hostsip
        marker: "# {mark} ANSIBLE HOSTS IP BLOCK"
        block: |
          web01: "{{ web01_out.instances[0].network_interfaces[0].private_ip_address }}"
          app01: "{{ app01_out.instances[0].network_interfaces[0].private_ip_address }}"
          rmq01: "{{ rmq01_out.instances[0].network_interfaces[0].private_ip_address }}"
          mc01: "{{ mc01_out.instances[0].network_interfaces[0].private_ip_address }}"
          db01: "{{ db01_out.instances[0].network_interfaces[0].private_ip_address }}"

    - name: Copy login key to provision_stack directory
      copy:
        src: loginkey_vpro.pem
        dest: provision-stack/loginkey_vpro.pem
        mode: 0400

    - name: Insert/Update inventory file provision-stack/inventory-vpro
      blockinfile:
        path: provision-stack/inventory-vpro
        block: |
          web01: ansible_host={{ web01_out.instances[0].network_interfaces[0].private_ip_address }}
          app01: ansible_host={{app01_out.instances[0].network_interfaces[0].private_ip_address }}
          rmq01: ansible_host={{rmq01_out.instances[0].network_interfaces[0].private_ip_address }}
          mc01: ansible_host={{mc01_out.instances[0].network_interfaces[0].private_ip_address }}
          db01: ansible_host={{db01_out.instances[0].network_interfaces[0].private_ip_address }}
          cntl: ansible_host=127.0.0.1 ansible_connection=local

          [websrvgrp]
          web01

          [appsrvgrp]
          app01

          [rmqsrvgrp]
          rmq01

          [mcsrvgrp]
          mc01

          [dbsrvgrp]
          db01

          [control]
          cntl

          [stack_inst:children]
          websrvgrp
          appsrvgrp
          rmqsrvgrp
          mcsrvgrp
          dbsrvgrp
          
          [stack_inst:vars]
          ansible_user=ubuntu
          ansible_ssh_private_key_file=loginkey_vpro
          #ansible_python_interpreter=/usr/bin/python3
